# Generated by Django 3.0.3 on 2020-07-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='client',
        ),
    ]
