# Generated by Django 3.0.3 on 2020-07-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_events_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='status',
            new_name='is_complete',
        ),
    ]
