# Generated by Django 3.0.3 on 2020-07-22 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200722_1927'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0002_auto_20200722_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contracts', to='accounts.Client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sales_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Client_Contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
