# Generated by Django 3.0.3 on 2020-07-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20200722_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='status',
            new_name='is_complete',
        ),
    ]
