# Generated by Django 3.0.3 on 2020-07-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200722_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
