# Generated by Django 3.0.3 on 2020-08-19 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('service_name', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50000)),
                ('is_done', models.BooleanField(blank=True, default=False, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('attendees', models.IntegerField()),
                ('additional_requirements', models.CharField(max_length=10000)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contract_Services', to='contracts.ContractModel')),
                ('sales_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Client_Service', to=settings.AUTH_USER_MODEL)),
                ('support_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Support_Services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
